version: "3"

services:
  app:
    build:
      context: .
    ports:
      - "8080:8080"
    volumes:
      - ./app /app
    command: >
      sh -c "python manage.py wait_for_db &&
              python manage.py migrate &&
              python manage.py runserver 0.0.0.0:8080"
    environment:
      - DB_HOST=db
      - DB_NAME=app
      - DB_USER=postgres
      - DB_PASS=supersecret
    depends_on:
      - db
      - cache

  db:
    image: postgres:14-alpine
    restart: always
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=postgres
      # Never put password unless on local machine. Use encrypted env variable
      - POSTGRES_PASSWORD=supersecret
    ports:
      5432:5432

  cache:
      image: redis:7-alpine
      command: >
        sh -c "redis-server"
      ports:
        6379:6379
